### ISSUE TITLE
src/tests.c:3561:52: error: dereferencing pointer to incomplete type «ECDSA_SIG {aka struct ECDSA_SIG_st}»

### ISSUE THREAD

**Issue by safocl** [thebitradio/Bitradio#1]
os archlinux, libsecp256k1, libgmp, Boost1.57, Openssl1.0.1p, Berkeley DB 4.8, QT5 

error when compiling (highlights "->"):
`src/tests.c:3561:52: error: dereferencing pointer to incomplete type 'ECDSA_SIG {aka struct ECDSA_SIG_st}'
         valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
`
[https://ptpb.pw/9zRP](url) full log

[https://i.imgur.com/hjgfyk9.png](url) screen

**Comment by jamilservicos** [comment]
In your log, the error does not appear, so we can not know the reason, but from what I saw you were doing separate compilations.
So please, let's say what you're trying to do and how you're trying to do.

This error really is related to openssl, so make sure all the dependencies of it are installed

see: https://github.com/thebitradio/Bitradio/blob/master/doc/build-unix.md

**Comment by jamilservicos** [comment]
If this solves your problem, do not forget to close this "issue" once it is resolved.
