### ISSUE TITLE
Have error

### ISSUE THREAD

**Issue by lopachuck** [thebitradio/Bitradio#15]
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wunused-function -Wunused-variable -fpermissive -Wconversion-null -g -DBOOST_SPIRIT_THREADSAFE -I/home/n0fear/Bitradio/src -I/home/n0fear/Bitradio/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -DENABLE_WALLET -I/home/n0fear/Bitradio/src/secp256k1/include -I/home/n0fear/Bitradio/src/leveldb/include -I/home/n0fear/Bitradio/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
In file included from alert.h:9:0,
                 from alert.cpp:6:
serialize.h:19:10: fatal error: boost/type_traits/is_fundamental.hpp: Нет такого файла или каталога
 #include <boost/type_traits/is_fundamental.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
makefile.unix:217: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1

**Comment by lopachuck** [comment]
System Kubuntu 18.04

**Comment by stormizrws** [comment]
Как решить проблему? 
src/qt/optionsmodel.cpp:17:25: фатальная ошибка: QNetworkProxy: Нет такого файла или каталога
компиляция прервана
