### ISSUE TITLE
Error with Hight Sierra dmg file.

### ISSUE THREAD

**Issue by liho26** [thebitradio/Bitradio#18]
App crashes under start in Mojave. 

Application Specific Information:
dyld: launch, loading dependent libraries
Dyld Error Message:

Library not loaded: @loader_path/libboost_system-mt.dylib
Referenced from: /Applications/BitRadio-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib

Reason: image not found

**Comment by BoubonicNugz** [comment]
High Sierra build has been pulled down in favor of the deterministic OSX build for the time being - please use that version.
