### ISSUE TITLE
Compilation does not complete in Ubuntu 16.04

### ISSUE THREAD

**Issue by COUPON4Vitamins** [thebitradio/Bitradio#3]
b.h:18:20: fatal error: db_cxx.h: No such file or directory
compilation terminated.
makefile.unix:217: recipe for target 'obj/init.o' failed
make: *** [obj/init.o] Error 1

**Comment by jamilservicos** [comment]
Just by putting the error, it does not help at all. We need to know what to do and how you try to do it.
For someone trying to help you.

**Comment by COUPON4Vitamins** [comment]
Thanks for the reply

This is the error I got when I did the last command as outlined in the README.md:
`make -f makefile.unix # Headless
`
However, today I tried to install the Bitradio client from scratch again and a different error appeared. I recorded my terminal output and uploaded to asciinema.org:
[](https://asciinema.org/a/134910

I hope this info helps to find out how to solve my install problem.

My box's specs:

```
./+o+-       liam@RAT
                  yyyyy- -yyyyyy+      OS: Ubuntu 16.04 xenial
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.4.0-92-generic
           .++ .:/++++++/-.+sss/`      Uptime: 1d 7h 32m
         .:++o:  /++++++++/:--:/-      Packages: 3542
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.3.48
       .:+o:+o/.          `+sssoo+/    Resolution: 1366x768
  .++/+:+oo+o:`             /sssooo.   DE: LXDE
 /+++//+:`oo+o               /::--:.   WM: OpenBox
 \+/+o+++`o++o               ++////.   WM Theme: Onyx
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Clearlooks [GTK2]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Lubuntu
        \+.++o+o``-````.:ohdhhhhh+     Font: Sans 10
         `:o+++ `ohhhhhhhhyo++os:      CPU: AMD Athlon II X2 220 @ 2.8GHz
           .o:`.syhhhhhhh/.oo++o`      GPU: Gallium 0.4 on NV4C
               /osyyyyyyo++ooo+++/     RAM: 3043MiB / 3699MiB
                   ````` +oo+++o\:    
                          `oo++.      

```

**Comment by jamilservicos** [comment]
Have you installed the necessary dependencies?
I posted a step by step in the forum, check if it helps.

[http://forum.bitrad.io/topic/420/debian-installation-problem/2](http://forum.bitrad.io/topic/420/debian-installation-problem/2)

Remembering that where it is:

    cd ../Bitradio-master/

Refers to the directory created by the "git clone" command, if you rename it or the directory is saved with another name, then use the new name.


If this solves your problem, do not forget to close this "issue" once it is resolved.

**Comment by COUPON4Vitamins** [comment]
# ** 😄 THANK YOU 👍**

btw: my git command gave me the folder bitradio-wallet, so thanks for telling me about the folder name
