### ISSUE TITLE
Link statically on Linux, fix building

### ISSUE THREAD

**Issue by pzmarzly** [thebitradio/Bitradio#6]
On Manjaro (so also on Arch) binary fails to load, since it searches for boost 1.55.1, while 1.65.1 libs are installed.

Also, manual build fails, log: [build_log.txt](https://github.com/thebitradio/Bitradio/files/1400413/build_log.txt)

**Comment by pzmarzly** [comment]
To build successfully on Arch or Manjaro:

1. Install `openssl-1.0`
2. Edit `src/secp256k1/src/tests.c` and add `#undef ENABLE_OPENSSL_TESTS`
3. Build with `env OPENSSL_INCLUDE_PATH=/usr/include/openssl-1.0 OPENSSL_LIB_PATH=/usr/lib/openssl-1.0 make -f makefile.unix`

**Comment by openpartners** [comment]
/Bitradio/src/alert.h:9:
/Bitradio/src/serialize.h:19:10: fatal error: 'boost/type_traits/is_fundamental.hpp' file not found
#include <boost/type_traits/is_fundamental.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [obj/alert.o] Error 1

**Comment by EvgenK88** [comment]
для установки кошелька нужно время
